server:
  port: 8090
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MuscleGeeker/spring-cloud-tutorial # 配置中心地址
          search-paths: microservice-config-repo # 若存在多个地址用','隔开
          username: # github用户名
          password: # github密码