server:
  port: 8080
spring:
  cloud:
    config:
      server:
        git:
          uri: https://git.oschina.net/musclegeeker/spring-cloud-config-repo
          search-paths:
            - aaa
            - bbb