spring:
  application:
    name: microservice-consumer-movie-feign-customizing
server:
  port: 7901
eureka:
  client:
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
logging:
  level:
    me.musclegeeker.cloud.feign.UserFeignClient: DEBUG
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 5000
#hystrix:
#  command:
#    default:
#      execution:
#        timeout:
#          enabled: false
feign:
  hystrix:
    enabled: false