server:
  port: 8900
eureka:
  client:
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka/
  instance:
    appname: microservice-consumer-movie-ribbon-hystrix
    instance-id: ${eureka.instance.appname}:${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true