server:
  port: 8900
eureka:
  client:
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    appname: micoservice-consumer-movie-feign-with-hystrix-fallbackfactory
    instance-id: ${eureka.instance.appname}:${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
logging:
  level:
    me.musclegeeker.cloud.feign.UserFeignClient: DEBUG