server:
  port: 8040
eureka:
  instance:
    appname: microservice-gateway-zuul-regx-exp
    prefer-ip-address: true
    instance-id: ${eureka.instance.appname}:${spring.cloud.client.ipAddress}:${server.port}
  client:
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka/