server:
  port: 8080
security:
  basic:
    enabled: true
  user:
    name: user
    password: password
spring:
  cloud:
    config:
      server:
        git:
          uri: https://git.oschina.net/musclegeeker/spring-cloud-config-repo