server:
  port: 8032
eureka:
  instance:
    appname: microservice-hystrix-turbine-path
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka/
turbine:
  aggregator:
    clusterConfig: default
  appConfig: microservice-consumer-movie-ribbon-hystrix-path
  clusterNameExpression: "'default'"

