server:
  port: 8033
eureka:
  instance:
    appname: microservice-hystrix-turbine-path
    prefer-ip-address: true
    instance-id: ${eureka.instance.appname}:${spring.cloud.client.ipAddress}:${server.port}
  client:
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka/
turbine:
  aggregator:
    clusterConfig: MICROSERVICE-CONSUMER-MOVIE-RIBBON-HYSTRIX-PATH
  appConfig: microservice-consumer-movie-ribbon-hystrix-path
  instanceUrlSuffix:
    MICROSERVICE-CONSUMER-MOVIE-RIBBON-HYSTRIX-PATH: /ribbon/hystrix.stream
